### ISSUE TITLE
Date Bug

### ISSUE THREAD

**Issue by AKAElias** [MapManagement/Countdown#3]
Datetimer can't go further than 175 days

**Comment by MapManagement** [comment]
At first I updated the whole project because of an older framework and Kotlin version. After that, I replicated that error a few times and hopefully found the bug. Using an integer type instead of long lead into an unwanted limit. It hopefully should be fixed now.
Simply just use the [newest release](https://github.com/MapManagement/Countdown/releases/tag/v3.2) and test it!
